# Generated by Django 5.0.3 on 2024-05-28 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_banner',
            field=models.ImageField(default=0, upload_to='course_banner/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='related_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
