# Generated by Django 5.0.6 on 2024-05-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_coursetaken_feedback_quizresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.IntegerField(blank=True, max_length=15),
        ),
    ]
