# Generated by Django 5.0.6 on 2024-05-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_answer_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
